config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/attend', to: 'guestlists#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :guestlists, foreign_key: :attended_event_id
  has_many :attendees, through: :guestlists 

  validates :name, presence: true

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }

  # def Event.past
  #   Event.where("date < ?", Time.now)
  # end

  # def Event.upcoming
  #   Event.where("date > ?", Time.now)
  # end
    
end

app/models/guestlist.rb
class Guestlist < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events_created, foreign_key: :creator_id, class_name: "Event"
  has_many :guestlists, foreign_key: :attendee_id
  has_many :attended_events, through: :guestlists

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    
    @event = current_user.events_created.build(event_params)
    if @event.save
      redirect_to current_user
    else
      flash.now[:danger] = "Give your event a name!"
      render 'new'
    end
  end
  
  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
    @events = Event.all
  end

  private
    def event_params
      params.require(:event).permit(:name, :location, :date)
    end
end

app/controllers/guestlists_controller.rb
class GuestlistsController < ApplicationController
  def create
    @guestlist = Guestlist.new
    @guestlist[:attendee_id] = session[:user_id]
    @guestlist[:attended_event_id] = params[:event_id]
    @guestlist.save
    redirect_to Event.find(params[:event_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in(user)
     
      redirect_to user
    else
      flash.now[:danger] = "User not found! Please try again"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    log_in @user
    redirect_to @user
  end
  
  def show
    @user = User.find(params[:id])
    @hosting_events = @user.events_created.upcoming
    @hosted_events = @user.events_created.past
    @attending_events = @user.attended_events.upcoming
    @attended_events = @user.attended_events.past
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guestlists_helper.rb
module GuestlistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<p>Upcoming Events:</p>

<% @upcoming_events.each do |event| %>
  <p><%= link_to "#{event.name}", event_path(event.id) %></p>
<% end %>

<p>Past Events:</p>

<% @past_events.each do |event| %>
  <p><%= link_to "#{event.name}", event_path(event.id) %></p>
<% end %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label :location %></p>
  <p><%= f.text_field :location %></p>
  <p><%= f.label :date %></p>
  <p><%= f.date_field :date %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/events/show.html.erb
<p><%= "Name: #{@event.name}" %></p>
<p><%= "Location: #{@event.location}" %></p>
<p><%= "Date: #{@event.date}" %></p>
<p><%= "Host: #{@event.creator.name}" %></p>
<p>Guests:</p>
<% @attendees.each do |attendees| %>
  <p><%= attendees.name %></p>
<% end %>
<% if !@attendees.include?(current_user) %>
<%= form_for(:guestlist, url: attend_path) do |f| %>
  <%= hidden_field_tag(:event_id, @event.id) %>
  <p><%= f.submit "Attend" %></p>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
Navigation Links:


<p><%= link_to "All Events", events_path %></p>
<% if logged_in? %>
  <p><%= link_to "Profile", current_user %></p>
  <p><%= link_to "Create An Event", new_event_path %>
  <p><%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <p><%= link_to "Signup", new_user_path %></p>
  <p><%= link_to "Login", login_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to(image_tag("private", height: 100, width: 100), root_path) %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/navigation' %>
    <% if logged_in? %>
    <p><%= "#{current_user.name} is logged in" %></p>
    <% else %>
    <p>Noone is currently logged in</p>
    <% end %>  

  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<p>
  Events you're hosting:
  <% @hosting_events.each do |event| %>
    <p><%= link_to "#{event.name}", event_path(event.id) %></p>
  <% end %>
</p>
<p>
  Events you're attending:
  <% @attending_events.each do |event| %>
    <p><%= link_to "#{event.name}", event_path(event.id) unless @hosting_events.include?(event)%></p>
  <% end %>
</p>
<p>
  Events you've hosted:
  <% @hosted_events.each do |event| %>
    <p><%= link_to "#{event.name}", event_path(event.id) %></p>
  <% end %>
</p>

<p>
  Events you've attended:
  <% @attended_events.each do |event| %>
    <p><%= link_to "#{event.name}", event_path(event.id) unless @hosted_events.include?(event)%></p>
  <% end %>
</p>

<%= @upcoming_events %>